repos:
- repo: https://github.com/hadolint/hadolint
  rev: v2.9.2
  hooks:
  - id: hadolint-docker
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.21.2
  hooks:
    - id: commitizen
      stages: [commit-msg]
